root: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
  - "react-app"
  - "react-app/jest"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "plugin:jsx-a11y/recommended"
  - "plugin:prettier/recommended"
plugins:
  - "only-warn"
ignorePatterns:
  - "dist/"
env:
  browser: true
settings:
  import/resolver:
    typescript: {}
rules:
  no-var: "warn"
  prefer-const: "warn"
  prettier/prettier: "warn"
  import/newline-after-import: "warn"
  quotes:
    - "warn"
    - "double"
    - avoidEscape: true
      allowTemplateLiterals: false
  sort-imports:
    - "warn"
    - ignoreDeclarationSort: true
  import/order:
    - "warn"
    - groups: [builtin, external, internal, parent, sibling, index]
      pathGroups:
        - pattern: "@/**"
          group: "internal"
      alphabetize:
        order: "asc"
