name: "Release"

on:
  push:
    branches:
      - "beta"
      - "alpha"
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
        description: "Draft release"
        default: false
      release_type:
        type: choice
        description: "Release type"
        default: "auto"
        options:
          - "auto"
          - "patch"
          - "minor"
          - "major"

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v2

      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install

      - name: "Run Build"
        run: pnpm run build

      - name: "Release Package 📦"
        run: pnpm dlx @jcwillox/semantic-release-config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SEMANTIC_RELEASE_GITHUB_DRAFT: ${{ inputs.draft }}
          SEMANTIC_RELEASE_FORCE_RELEASE: ${{ inputs.release_type }}
